modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''

[[dependencies.bixis]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.bixis]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.bixis]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.2,)"
    ordering="NONE"
    side="BOTH"
